/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package files;

/**
 *
 * @author Acer
 */
import java.awt.Color;
import java.io.*;
import java.util.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
public class main extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    ArrayList<String> depart;
    public main() {
        super("WTM Generator");
        initComponents();
        
    }
public void reset()
{
    File s=new File("school.txt");
    File t=new File("trainer.txt");
    File m=new File("module.txt");
    File l=new File("level.txt");
    File d=new File("department.txt");
    int msg=JOptionPane.showConfirmDialog(null, "You are about to reset all information.\n Are you sure to proceed?", "Reset", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
    if(msg==JOptionPane.YES_OPTION)
    {
       
      if(  s.delete() && t.delete() && m.delete() && l.delete() && d.delete())
      {
          JOptionPane.showMessageDialog(null,"Information reset");
          dispose();
      }
      else
      {
         JOptionPane.showMessageDialog(null,"Information not reset"); 
      }
        
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bkpanel = new javax.swing.JPanel();
        hvpanel = new javax.swing.JPanel();
        btlevel = new javax.swing.JButton();
        btrainer = new javax.swing.JButton();
        pground = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbname = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        lbmanager = new javax.swing.JLabel();
        txtmanager = new javax.swing.JTextField();
        lbvmanager = new javax.swing.JLabel();
        txtvmanager = new javax.swing.JTextField();
        lbtel = new javax.swing.JLabel();
        txttel = new javax.swing.JTextField();
        lbmail = new javax.swing.JLabel();
        txtmail = new javax.swing.JTextField();
        lbpro = new javax.swing.JLabel();
        txtpro = new javax.swing.JTextField();
        lbdi = new javax.swing.JLabel();
        txtdi = new javax.swing.JTextField();
        lbse = new javax.swing.JLabel();
        txtse = new javax.swing.JTextField();
        lbnber = new javax.swing.JLabel();
        txtnber = new javax.swing.JTextField();
        lbox = new javax.swing.JLabel();
        txtbox = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbdep = new javax.swing.JTable();
        btsave = new javax.swing.JButton();
        btmodule = new javax.swing.JButton();
        lbinfo = new javax.swing.JLabel();
        btgenerate = new javax.swing.JButton();
        btreset = new javax.swing.JButton();
        main_title = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bkpanel.setBackground(new java.awt.Color(153, 153, 153));

        hvpanel.setBackground(new java.awt.Color(204, 204, 204));
        hvpanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btlevel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btlevel.setText("Level");
        btlevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btlevelActionPerformed(evt);
            }
        });

        btrainer.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btrainer.setText("Trainer");
        btrainer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btrainerActionPerformed(evt);
            }
        });

        pground.setBackground(new java.awt.Color(204, 204, 204));
        pground.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("School record");

        lbname.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbname.setText("Name:");

        txtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameActionPerformed(evt);
            }
        });

        lbmanager.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbmanager.setText("Manager:");

        lbvmanager.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbvmanager.setText("V/Manager:");

        lbtel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbtel.setText("Telephone:");

        lbmail.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbmail.setText("Email:");

        lbpro.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbpro.setText("Province:");

        lbdi.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbdi.setText("District:");

        lbse.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbse.setText("Sector:");

        lbnber.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbnber.setText("Number of department:");

        lbox.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbox.setText("P.O Box");

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setText("Go");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tbdep.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Department"
            }
        ));
        jScrollPane1.setViewportView(tbdep);

        btsave.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btsave.setText("Save");
        btsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pgroundLayout = new javax.swing.GroupLayout(pground);
        pground.setLayout(pgroundLayout);
        pgroundLayout.setHorizontalGroup(
            pgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pgroundLayout.createSequentialGroup()
                .addContainerGap(103, Short.MAX_VALUE)
                .addGroup(pgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pgroundLayout.createSequentialGroup()
                        .addGroup(pgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbmanager)
                            .addComponent(lbname)
                            .addComponent(lbvmanager)
                            .addComponent(lbtel)
                            .addComponent(lbmail)
                            .addComponent(lbpro)
                            .addComponent(lbdi)
                            .addComponent(lbse)
                            .addComponent(lbnber)
                            .addComponent(lbox))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtmanager)
                            .addComponent(txtname)
                            .addComponent(txtvmanager)
                            .addComponent(txttel)
                            .addComponent(txtmail)
                            .addComponent(txtpro)
                            .addComponent(txtdi)
                            .addComponent(txtse)
                            .addComponent(txtbox)
                            .addGroup(pgroundLayout.createSequentialGroup()
                                .addComponent(txtnber, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(10, 10, 10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pgroundLayout.createSequentialGroup()
                        .addComponent(btsave, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(pgroundLayout.createSequentialGroup()
                .addGap(328, 328, 328)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pgroundLayout.setVerticalGroup(
            pgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pgroundLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(pgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pgroundLayout.createSequentialGroup()
                        .addGroup(pgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbname)
                            .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbmanager)
                            .addComponent(txtmanager, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbvmanager)
                            .addComponent(txtvmanager, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbtel)
                            .addComponent(txttel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbmail)
                            .addComponent(txtmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbox)
                            .addComponent(txtbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbpro)
                            .addComponent(txtpro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbdi)
                            .addComponent(txtdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbse)
                            .addComponent(txtse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(pgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbnber)
                            .addComponent(txtnber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btsave))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        btmodule.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btmodule.setText("Module");
        btmodule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmoduleActionPerformed(evt);
            }
        });

        lbinfo.setBackground(new java.awt.Color(153, 255, 153));
        lbinfo.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbinfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        btgenerate.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btgenerate.setText("Generate timetable");
        btgenerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btgenerateActionPerformed(evt);
            }
        });

        btreset.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btreset.setText("Reset all");
        btreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btresetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout hvpanelLayout = new javax.swing.GroupLayout(hvpanel);
        hvpanel.setLayout(hvpanelLayout);
        hvpanelLayout.setHorizontalGroup(
            hvpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hvpanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(hvpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbinfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(hvpanelLayout.createSequentialGroup()
                        .addComponent(btlevel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btrainer, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btmodule, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btgenerate, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btreset, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30))
        );
        hvpanelLayout.setVerticalGroup(
            hvpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hvpanelLayout.createSequentialGroup()
                .addGroup(hvpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btlevel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btrainer, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btmodule, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btgenerate, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btreset, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbinfo, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
        );

        main_title.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        main_title.setText("WTM generator");

        javax.swing.GroupLayout bkpanelLayout = new javax.swing.GroupLayout(bkpanel);
        bkpanel.setLayout(bkpanelLayout);
        bkpanelLayout.setHorizontalGroup(
            bkpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bkpanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(hvpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bkpanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(main_title)
                .addGap(338, 338, 338))
        );
        bkpanelLayout.setVerticalGroup(
            bkpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bkpanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(main_title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hvpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bkpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bkpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btlevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btlevelActionPerformed
        // TODO add your handling code here:
        new_level nl;
        nl=new new_level();
        nl.setVisible(true);
        
    }//GEN-LAST:event_btlevelActionPerformed

    private void txtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameActionPerformed

    private void btsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsaveActionPerformed
        // TODO add your handling code here:
        PrintWriter writer;
        PrintWriter dp;
        
            try {
                writer=new PrintWriter("school.txt","UTF-8");
                writer.println("SCHOOL INFORMATION");
                writer.println("");
                writer.println("Name:\t"+txtname.getText());
                writer.println("Manager:\t"+txtmanager.getText());
                writer.println("Head teacher:\t"+txtvmanager.getText());
                writer.println("Telephone:\t"+txttel.getText());
                writer.println("Email:\t"+txtmail.getText());
                writer.println("P.O Box:\t"+txtbox.getText());
                writer.println("Province:\t"+txtpro.getText());
                writer.println("District:\t"+txtdi.getText());
                writer.println("Sector:\t"+txtse.getText());
                writer.println("");
                if(depart.size()>=1)
                {
                    dp=new PrintWriter("department.txt","UTF-8");
                     dp.println("DEPARTMENTS");
                     dp.println("");
                    int s=0;
                    while(s<depart.size())
                    {
                    dp.println(depart.get(s));
                    s++;
                    }
                    dp.close();
                }
               lbinfo.setText("School and department information added");
               lbinfo.setForeground(Color.blue);
               
                writer.close();
                
            } catch (FileNotFoundException | UnsupportedEncodingException e) {
                JOptionPane.showMessageDialog(null, e);
            }
        
        
        
    }//GEN-LAST:event_btsaveActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int n;
        String dep;
        DefaultTableModel d;
        d=new DefaultTableModel();
        Object[] col=new Object[1];
        col[0]="Departments";
        d.setColumnIdentifiers(col);
        Object r[]=new Object[1];
        depart=new ArrayList();
        n=Integer.valueOf(txtnber.getText());
        for(int i=1;i<=n;i++)
        {
        dep=JOptionPane.showInputDialog(null, "Department:\n "+String.valueOf(i), "Enter department number", JOptionPane.INFORMATION_MESSAGE);
        depart.add(dep);
        r[0]=dep;
        d.addRow(r);
        }
        tbdep.setModel(d);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btrainerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btrainerActionPerformed
        // TODO add your handling code here:
        new_trainer tr;
        tr=new new_trainer();
        tr.setVisible(true);
    }//GEN-LAST:event_btrainerActionPerformed

    private void btmoduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmoduleActionPerformed
        // TODO add your handling code here:
        new_module m;
        m=new new_module();
        m.setVisible(true);
    }//GEN-LAST:event_btmoduleActionPerformed

    private void btgenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btgenerateActionPerformed
        // TODO add your handling code here:
        shuffle f = new shuffle();
        f.load();
        
    }//GEN-LAST:event_btgenerateActionPerformed

    private void btresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btresetActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_btresetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bkpanel;
    private javax.swing.JButton btgenerate;
    private javax.swing.JButton btlevel;
    private javax.swing.JButton btmodule;
    private javax.swing.JButton btrainer;
    private javax.swing.JButton btreset;
    private javax.swing.JButton btsave;
    private javax.swing.JPanel hvpanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbdi;
    private javax.swing.JLabel lbinfo;
    private javax.swing.JLabel lbmail;
    private javax.swing.JLabel lbmanager;
    private javax.swing.JLabel lbname;
    private javax.swing.JLabel lbnber;
    private javax.swing.JLabel lbox;
    private javax.swing.JLabel lbpro;
    private javax.swing.JLabel lbse;
    private javax.swing.JLabel lbtel;
    private javax.swing.JLabel lbvmanager;
    private javax.swing.JLabel main_title;
    private javax.swing.JPanel pground;
    private javax.swing.JTable tbdep;
    private javax.swing.JTextField txtbox;
    private javax.swing.JTextField txtdi;
    private javax.swing.JTextField txtmail;
    private javax.swing.JTextField txtmanager;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtnber;
    private javax.swing.JTextField txtpro;
    private javax.swing.JTextField txtse;
    private javax.swing.JTextField txttel;
    private javax.swing.JTextField txtvmanager;
    // End of variables declaration//GEN-END:variables
}
