/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package files;

/**
 *
 * @author Acer
 */
import java.awt.Color;
import java.io.*;
import java.nio.file.*;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;
import javax.swing.DefaultListModel;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
public class new_trainer extends javax.swing.JFrame {

    /**
     * Creates new form new_module
     */
    public new_trainer() {
        initComponents();
        load_trainer();
    }
public void load_trainer()
{
    
    DefaultTableModel t=new DefaultTableModel();
    Object[] col=new Object[3];
        col[0]="Code";
        col[1]="Name";
        col[2]="Day off";
        t.setColumnIdentifiers(col);
    Path p;
        try{
        p =Paths.get("trainer.txt");
        List<String> l=Files.lines(p).collect(Collectors.toList());
        String s="TRAINERS";
        boolean in=l.stream().anyMatch(g->g.equals(s));
        if(in)
        {
        FileReader fr=new FileReader("trainer.txt");
        BufferedReader rd=new BufferedReader(fr);
        boolean is=false;
        String search;
        ArrayList<String> ls=new ArrayList();
        while((search=rd.readLine())!=null)
        {
            if(search.contains(s))
            {
                is=true;
                continue;
            }
           
            if(is && !search.isEmpty())
            {
               ls.add(search);
            
            }
            
       }
        Object[] elements=new Object[3];
        String[] parts;
        for(int a=0;a<ls.size();a++)
        {
            parts=ls.get(a).split(",");
         //JOptionPane.showMessageDialog(null, ls.get(a));   
        elements[0]=parts[0];
         elements[1]=parts[1];
          elements[2]=parts[2];
        t.addRow(elements);
        }
       tbtrain.setModel(t);
        }
        }
        catch(IOException e)
        {
            
        }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bkpanel = new javax.swing.JPanel();
        hvpanel = new javax.swing.JPanel();
        pground = new javax.swing.JPanel();
        lbtrain = new javax.swing.JLabel();
        lbname = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbtrain = new javax.swing.JTable();
        btsave = new javax.swing.JButton();
        lbinfo = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        lsday = new javax.swing.JList<>();
        lbvmanager1 = new javax.swing.JLabel();
        main_title = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        bkpanel.setBackground(new java.awt.Color(153, 153, 153));

        hvpanel.setBackground(new java.awt.Color(204, 204, 204));
        hvpanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        pground.setBackground(new java.awt.Color(204, 204, 204));
        pground.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N

        lbtrain.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbtrain.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbtrain.setText("Trainer record");

        lbname.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbname.setText("Name:");

        txtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameActionPerformed(evt);
            }
        });

        tbtrain.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tbtrain.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Trainers"
            }
        ));
        jScrollPane1.setViewportView(tbtrain);

        btsave.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btsave.setText("Save");
        btsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsaveActionPerformed(evt);
            }
        });

        lbinfo.setBackground(new java.awt.Color(153, 255, 153));
        lbinfo.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbinfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lsday.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lsday.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "None", "Monday", "Tuesday", "Wenesday", "Thursday", "Friday", "Saturday", "Sunday" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(lsday);

        lbvmanager1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbvmanager1.setText("Day off:");

        javax.swing.GroupLayout pgroundLayout = new javax.swing.GroupLayout(pground);
        pground.setLayout(pgroundLayout);
        pgroundLayout.setHorizontalGroup(
            pgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pgroundLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(pgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbname)
                    .addComponent(lbvmanager1))
                .addGap(31, 31, 31)
                .addGroup(pgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtname, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
            .addGroup(pgroundLayout.createSequentialGroup()
                .addGap(328, 328, 328)
                .addComponent(lbtrain, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pgroundLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btsave, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(325, 325, 325))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pgroundLayout.createSequentialGroup()
                .addComponent(lbinfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pgroundLayout.setVerticalGroup(
            pgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pgroundLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(lbtrain, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(pgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(pgroundLayout.createSequentialGroup()
                        .addGroup(pgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbname)
                            .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(pgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbvmanager1)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btsave)
                .addGap(3, 3, 3)
                .addComponent(lbinfo, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout hvpanelLayout = new javax.swing.GroupLayout(hvpanel);
        hvpanel.setLayout(hvpanelLayout);
        hvpanelLayout.setHorizontalGroup(
            hvpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hvpanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(pground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(30, 30, 30))
        );
        hvpanelLayout.setVerticalGroup(
            hvpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hvpanelLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(pground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        main_title.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        main_title.setText("WTM generator");

        javax.swing.GroupLayout bkpanelLayout = new javax.swing.GroupLayout(bkpanel);
        bkpanel.setLayout(bkpanelLayout);
        bkpanelLayout.setHorizontalGroup(
            bkpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bkpanelLayout.createSequentialGroup()
                .addGroup(bkpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bkpanelLayout.createSequentialGroup()
                        .addGap(365, 365, 365)
                        .addComponent(main_title))
                    .addGroup(bkpanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(hvpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bkpanelLayout.setVerticalGroup(
            bkpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bkpanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(main_title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hvpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bkpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bkpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameActionPerformed

    private void btsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsaveActionPerformed
        // TODO add your handling code here:
        Path p;
        File f=new File("trainer.txt");
        try{
            if(f.exists())
                {
        p =Paths.get("trainer.txt");
        List<String> l=Files.lines(p).collect(Collectors.toList());
       String s="TRAINERS";
        boolean in=l.stream().anyMatch(g->g.equals(s));
        if(in)
        {
         FileWriter wr;
            BufferedWriter br;
            BufferedReader rd;
            String ln;
            boolean is=false;
            
                    FileReader rder;
                    rder=new FileReader(f);
                    rd=new BufferedReader(rder);
                    int nber=1;
                    while((ln=rd.readLine())!=null)
                  {
            if(ln.equals("TRAINERS"))
            {
                is=true;
                rd.readLine();
                rd.readLine();
            }
            if(is)
            {
              nber++; 
            }
                  }
                    wr=new FileWriter(f,true);
                    br=new BufferedWriter(wr);
                    br.newLine();
                    br.write("0"+String.valueOf(nber)+", \t"+txtname.getText()+", \t"+lsday.getSelectedValue());
                    lbinfo.setText("Trainer added");
                    lbinfo.setForeground(Color.blue);
                    br.close();
                    rd.close();
           }
        else
        {
         FileWriter wr;
         BufferedWriter br;
         wr=new FileWriter(f,true);
                    br=new BufferedWriter(wr);
                     br.write("TRAINERS");
                     br.newLine();
                     br.write("");
                     br.newLine();
                    br.write("01, \t"+txtname.getText()+", \t"+lsday.getSelectedValue());
                    lbinfo.setText("Trainer added");
                    lbinfo.setForeground(Color.blue);
                    br.close();
                    wr.close();    
        }
        }
            else
            {
                PrintWriter writer;
                 writer=new PrintWriter("trainer.txt","UTF-8");
                writer.println("TRAINERS");
                writer.println("");
                writer.println("01, \t"+txtname.getText()+", \t"+lsday.getSelectedValue());
                lbinfo.setText("Trainer added");
                lbinfo.setForeground(Color.blue);
                writer.close();
            }
            load_trainer();
        }
        catch(IOException e)
        {
          JOptionPane.showMessageDialog(null,e);  
        }
        

    }//GEN-LAST:event_btsaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(new_trainer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(new_trainer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(new_trainer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(new_trainer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new new_trainer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bkpanel;
    private javax.swing.JButton btsave;
    private javax.swing.JPanel hvpanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbinfo;
    private javax.swing.JLabel lbname;
    private javax.swing.JLabel lbtrain;
    private javax.swing.JLabel lbvmanager1;
    private javax.swing.JList<String> lsday;
    private javax.swing.JLabel main_title;
    private javax.swing.JPanel pground;
    private javax.swing.JTable tbtrain;
    private javax.swing.JTextField txtname;
    // End of variables declaration//GEN-END:variables
}
